name: json_widget_generator
description: Json Widget generator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"



flutter:

  uses-material-design: true

dependencies:
  equatable: ^2.0.3

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.21.4